import Head from 'next/head'
import styled from 'styled-components'
import Header from '../components/Header'
import Navbar from '../components/Nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MoviesNow.se</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MoviesApp>
        <Header />
        <Navbar />
      </MoviesApp>

    </div>
  )
}

const MoviesApp = styled.main`
  width: 95vw;
  max-width: 1200px;
  margin: 0 auto;
  padding: 30px 10px;
`
