import Head from 'next/head'
import moviesRoot from '../utils/request'
import styled from 'styled-components'
import Header from '../components/Header'
import Navbar from '../components/Nav'
import Results from '../components/Results'

export const getServerSideProps = async (context) => {
  const genre = context.query.genre
  
  const res = await fetch(`https://api.themoviedb.org/3${moviesRoot[genre]?.url || moviesRoot.Trending.url}`)
  const data = await res.json()

  return {
    props: {
      movies: data?.results
    }
  }
}

export default function Home({movies}) {
  return (
    <div>

      <Head>
        <title>MoviesNow.se</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MoviesApp>
        <Header />
        <Navbar />
        <Results movies={movies} />
      </MoviesApp>

    </div>
  )
}

const MoviesApp = styled.main`
  width: 95vw;
  max-width: 1100px;
  margin: 0 auto;
  padding: 30px 10px;
`
